# Generated by Django 5.2 on 2025-05-08 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('data_contratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('professor_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_responsaveis', to='app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('periodo', models.CharField(choices=[('manha', 'manha'), ('tarde', 'tarde'), ('noite', 'noite')], max_length=6)),
                ('sala_reservada', models.CharField(max_length=50)),
                ('disciplina_associada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.disciplina')),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.professor')),
            ],
        ),
    ]
