# Generated by Django 5.1.7 on 2025-03-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
                ('data', models.DateField()),
                ('local', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
